//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OT_Performance_Tracer.forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class fSearch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OT_Performance_Tracer.forms.fSearch", typeof(fSearch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string Allfiles {
            get {
                return ResourceManager.GetString("Allfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current File.
        /// </summary>
        public static string SingleFile {
            get {
                return ResourceManager.GetString("SingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Request.
        /// </summary>
        public static string SingleThread {
            get {
                return ResourceManager.GetString("SingleThread", resourceCulture);
            }
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            txtSearchString = new TextBox();
            cFirst = new Button();
            cNext = new Button();
            label1 = new Label();
            cScope = new ComboBox();
            SuspendLayout();
            // 
            // txtSearchString
            // 
            txtSearchString.Location = new Point(12, 12);
            txtSearchString.Name = "txtSearchString";
            txtSearchString.Size = new Size(652, 23);
            txtSearchString.TabIndex = 0;
            // 
            // cFirst
            // 
            cFirst.Location = new Point(508, 46);
            cFirst.Name = "cFirst";
            cFirst.Size = new Size(75, 23);
            cFirst.TabIndex = 3;
            cFirst.Text = "First";
            cFirst.UseVisualStyleBackColor = true;
            cFirst.Click += cFirst_Click;
            // 
            // cNext
            // 
            cNext.Location = new Point(589, 45);
            cNext.Name = "cNext";
            cNext.Size = new Size(75, 23);
            cNext.TabIndex = 4;
            cNext.Text = "Next";
            cNext.UseVisualStyleBackColor = true;
            cNext.Click += cNext_Click;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Location = new Point(12, 50);
            label1.Name = "label1";
            label1.Size = new Size(39, 15);
            label1.TabIndex = 1;
            label1.Text = "Scope";
            // 
            // cScope
            // 
            cScope.FormattingEnabled = true;
            cScope.Location = new Point(57, 46);
            cScope.Name = "cScope";
            cScope.Size = new Size(145, 23);
            cScope.TabIndex = 2;
            // 
            // fSearch
            // 
            AcceptButton = cFirst;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(676, 81);
            Controls.Add(cScope);
            Controls.Add(label1);
            Controls.Add(cNext);
            Controls.Add(cFirst);
            Controls.Add(txtSearchString);
            FormBorderStyle = FormBorderStyle.FixedDialog;
            MaximizeBox = false;
            MinimizeBox = false;
            Name = "fSearch";
            Text = "fSearch";
            FormClosing += fSearch_FormClosing;
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private TextBox txtSearchString;
        private Button cFirst;
        private Button cNext;
        private Label label1;
        private ComboBox cScope;
    }
}
